language: java

env:
  matrix:
    - JAVA_FOR_TESTS=OpenJDK7
    - JAVA_FOR_TESTS=Oracle7
    - JAVA_FOR_TESTS=Oracle8

before_script:
  - ant setupJava{$JAVA_FOR_TESTS}TestEnvironment
  - mkdir -p lib/test/
  - cp android-lib/* lib/test/

script:
  - ant test

notifications:
  email: true
